services:
  db:
    image: postgres:16
    container_name: smart-supply-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smartsupply
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


  data-service:
    build:
      context: ../services/data-service
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8001:8000"

  ml-service:
    build:
      context: ../services/ml-service
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      DATA_SERVICE_URL: http://data-service:8000
    depends_on:
      data-service:
        condition: service_started
    ports:
      - "8002:8000"

  alert-service:
    build:
      context: ../services/alert-service
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      DATA_SERVICE_URL: http://data-service:8000
      ML_SERVICE_URL: http://ml-service:8000
    depends_on:
      db:
        condition: service_healthy
      ml-service:
        condition: service_started
    ports:
      - "8003:8000"

volumes:
  pgdata:
